config/routes.rb
Rails.application.routes.draw do
  root'items#index'


  resources :items
  
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :list, dependent: :destroy
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@items = Item.all
  end

  def show
  	@item = Item.find(params[:id])
  end

  def new
  	@item = Item.new
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def update
  	@item = Item.find(params[:id])
  	if @item.update(item_params)
  		redirect_to item_path(@item)
  	else
  		render :edit
  	end
  end

  def destroy
  	Item.find(params[:id]).destroy
  	redirect_to items_path
  end

  def create
  	@item = Item.new(item_params)
  	if @item.save
  		redirect_to items_path
  	else
  		render :new
  	end
  end

  private

  def item_params
  	params.require(:item).permit(:name, :description, :completion)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.label :completion %>
	<%= f.check_box :completion %>
	<%= f.submit%>
<% end %>

app/views/items/edit.html.erb
<h1>Editiing an item <%= @item.name %></h1>
<br />

<%= render ('form') %>

app/views/items/index.html.erb
<h1>Todo list2</h1>
<br />


<% if @items.any? %>

	<ul>
		<% @items.each do |item| %>
			<li>
				<%= link_to item.name, item_path(item) %>
			</li>
		<% end %>
	</ul>
	<% else %>
		<h3>There are no items on the list please add some</h3>
<% end %>

<%= link_to 'New items',new_item_path %>

app/views/items/new.html.erb
<h1>Create a new item</h1>
<br />

<%= render ('form') %>

<%= link_to 'All items on the list', items_path %>

app/views/items/show.html.erb
<h1>The Task of <%= @item.name%> info:</h1>
<br />

<h2><%= @item.name %></h2>
	<p><%= @item.description %></p>
	<p><%= @item.completion %></p>

<%= link_to 'Edit item', edit_item_path(@item) %>

<%= link_to 'Delete', item_path(@item), method: :delete %>

<%= link_to 'All items on the list', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>